[package]
name = "preflate-rs"
version = "0.6.0"
edition = "2021"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]
license = "Apache-2.0"
rust-version = "1.70"
description = "Rust port of Preflate compression library"
readme = "README.md"
repository = "https://github.com/microsoft/preflate-rs"

exclude = [
    "samples/*",
    "tests/*",
    "util/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug=true

[dependencies]
anyhow = { version="1.0", features = ["backtrace"]}
byteorder = "1.4"
cabac = "0.6.0"
default-boxed = "0.2"
zstd = "0.13.0"

[dev-dependencies]
crc32fast = "1.3"
libz-sys = "1.1"
libdeflate-sys = "1.19"
libz-ng-sys="1.1.12"
miniz_oxide="0.7.1"

[lib]
crate-type = ["cdylib","lib"]