[package]
name = "preflate-rs"
version = "0.3.0"
edition = "2021"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]
license = "Apache-2.0"
rust-version = "1.70"
description = "Rust port of Preflate compression library"
readme = "README.md"
repository = "https://github.com/microsoft/preflate-rs"

exclude = [
    "tests/*",
    "util/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug=true

[dependencies]
anyhow = { version="1.0", features = ["backtrace"]}
byteorder = "1.4"
cabac = "0.6.0"
default-boxed = "0.2"
clap = { version="4.4", features = ["derive"]}

[dev-dependencies]
crc32fast = "1.3"
libz-sys = "1.1"
flate2 = "1.0"

[[bin]]
name = "preflate_util"
path = "src/main.rs"
