[package]
name = "preflate_rs"
version = "0.1.0"
edition = "2021"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug=true

[dependencies]
anyhow = { version="1.0", features = ["backtrace"]}
byteorder = "1.4"
crc32fast = "1.3"
libz-sys = "1.1"
flate2 = "1.0"
cabac = "0.4"
default-boxed = "0.2"
