[package]
name = "preflate_util"
edition = "2024"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]
license = "Apache-2.0"
rust-version = "1.85"

[dependencies]
preflate-rs = { path = "../lib" }
simple-log = "2.3"


[[bin]]
name = "preflate_util"