[package]
name = "preflate_util"
version = "0.1.0"
edition = "2021"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug=true

[dependencies]
anyhow = { version="1.0", features = ["backtrace"]}
byteorder = "1.4"
cabac = "0.6.0"
clap = { version = "4.4", features = ["derive"] }
default-boxed = "0.2"
crc32fast = "1.3"
libz-sys = "1.1"
flate2 = "1.0"
preflate_rs = { path = ".." }
walkdir = "2.3"
zstd = "0.13.0"

[[bin]]
name = "preflate_util"
