[package]
name = "preflate_util"
edition = "2021"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]
license = "Apache-2.0"
rust-version = "1.82"

[dependencies]
preflate-rs = { path = "../lib" }

[[bin]]
name = "preflate_util"