[package]
name = "preflate_util"
version = "0.2.0"
edition = "2021"
authors = ["Kristof Roomp <kristofr@microsoft.com>"]
license = "Apache-2.0"
rust-version = "1.70"

[dependencies]
preflate-rs = { path = "../lib" }

[[bin]]
name = "preflate_util"